"""
Pure grid algorithms: distances, paths, cycles. No game or snake concepts.
Inputs/outputs use only numbers, (row, col), or lists/sets of cells.
Used by strategies and testable in isolation.
"""
def manhattan_distance(row1: int, col1: int, row2: int, col2: int) -> int:
    """Distance between two cells when moving only horizontally/vertically."""
    return abs(row2 - row1) + abs(col2 - col1)


# Hamilton cycle generated by AI
def hamiltonian_cycle(rows, cols, start_row, start_col):

    if rows * cols == 1:
        return [(start_row, start_col)]

    if rows > 1 and cols > 1 and rows % 2 == 1 and cols % 2 == 1:
        raise ValueError("No Hamiltonian cycle possible")

    start = (start_row, start_col)
    total_cells = rows * cols

    path = [start]
    visited = {start}

    directions = [(-1,0),(1,0),(0,-1),(0,1)]

    def is_valid(r,c):
        return 0 <= r < rows and 0 <= c < cols and (r,c) not in visited

    def onward_moves(r,c):
        """Count how many moves are possible from this cell."""
        count = 0
        for dr,dc in directions:
            nr,nc = r+dr,c+dc
            if is_valid(nr,nc):
                count += 1
        return count

    def backtrack():

        if len(path) == total_cells:
            r,c = path[-1]
            sr,sc = start
            if abs(r-sr) + abs(c-sc) == 1:
                return True
            return False

        r,c = path[-1]

        neighbors = []
        for dr,dc in directions:
            nr,nc = r+dr,c+dc
            if is_valid(nr,nc):
                neighbors.append((nr,nc))

        neighbors.sort(key=lambda cell: onward_moves(cell[0],cell[1]))

        for nr,nc in neighbors:

            visited.add((nr,nc))
            path.append((nr,nc))

            if backtrack():
                return True

            path.pop()
            visited.remove((nr,nc))

        return False

    if backtrack():
        return path
    else:
        raise ValueError("No Hamiltonian cycle found")
