
# Hamilton cycle generated by AI
def hamiltonian_cycle(rows, cols, start_row, start_col):
    # Quick feasibility check
    if rows * cols == 1:
        return [(start_row, start_col)]
    
    if rows > 1 and cols > 1 and rows % 2 == 1 and cols % 2 == 1:
        raise ValueError  # No Hamiltonian cycle possible

    total_cells = rows * cols
    start = (start_row, start_col)
    path = [start]
    visited = set(path)

    directions = [(-1, 0), (1, 0), (0, -1), (0, 1)]

    def is_valid(r, c):
        return 0 <= r < rows and 0 <= c < cols and (r, c) not in visited

    # DFS
    def backtrack():
        if len(path) == total_cells:
            # Check if last cell connects back to start
            r, c = path[-1]
            sr, sc = start
            if abs(r - sr) + abs(c - sc) == 1:
                path.append(start)  # Close the cycle
                return True
            return False

        r, c = path[-1]

        for dr, dc in directions:
            nr, nc = r + dr, c + dc
            if is_valid(nr, nc):
                visited.add((nr, nc))
                path.append((nr, nc))

                if backtrack():
                    return True

                visited.remove((nr, nc))
                path.pop()

        return False

    if backtrack():
        path.pop()
        return path
    else:
        raise ValueError
