import math
from collections import defaultdict, deque
import heapq
from itertools import combinations

"""
Pure grid algorithms: distances, paths, cycles. No game or snake concepts.
Inputs/outputs use only numbers, (row, col), or lists/sets of cells.
Used by strategies and testable in isolation.
"""

class Problem(object):
    """The abstract class for a formal problem. A new domain subclasses this,
    overriding `actions` and `results`, and perhaps other methods.
    The default heuristic is 0 and the default action cost is 1 for all states.
    When yiou create an instance of a subclass, specify `initial`, and `goal` states 
    (or give an `is_goal` method) and perhaps other keyword args for the subclass."""

    def __init__(self, initial=None, goal=None, **kwds): 
        self.__dict__.update(initial=tuple(initial), goal=tuple(goal), **kwds) 
        
    def actions(self, state):        raise NotImplementedError
    def result(self, state, action): raise NotImplementedError
    def is_goal(self, state):        return state == self.goal
    def action_cost(self, s, a, s1): return 1
    def h(self, node):               return 0
    
    def __str__(self):
        return '{}({!r}, {!r})'.format(
            type(self).__name__, self.initial, self.goal)
    

class Node:
    "A Node in a search tree."
    def __init__(self, state, parent=None, action=None, path_cost=0):
        self.__dict__.update(state=state, parent=parent, action=action, path_cost=path_cost)

    def __repr__(self): return '<{}>'.format(self.state)
    def __len__(self): return 0 if self.parent is None else (1 + len(self.parent))
    def __lt__(self, other): return self.path_cost < other.path_cost
    
    
failure = Node('failure', path_cost=math.inf) # Indicates an algorithm couldn't find a solution.
cutoff  = Node('cutoff',  path_cost=math.inf) # Indicates iterative deepening search was cut off.
    
    
def expand(problem, node):
    "Expand a node, generating the children nodes."
    s = node.state
    for action in problem.actions(s):
        s1 = problem.result(s, action)
        cost = node.path_cost + problem.action_cost(s, action, s1)
        yield Node(s1, node, action, cost)
        

def path_actions(node):
    "The sequence of actions to get to this node."
    if node.parent is None:
        return []  
    return path_actions(node.parent) + [node.action]


def path_states(node):
    "The sequence of states to get to this node."
    if node in (cutoff, failure, None): 
        return []
    return path_states(node.parent) + [node.state]


class SnakeProblem(Problem):
    
    def actions(self, state): 
        """The places neighboring `state`."""
        return self.grid.neighbors[state]
    
    def result(self, state, action):
        """Go to the `action` place, if the map says that is possible."""
        return action if action in self.grid.neighbors[state] else state
    
    def action_cost(self, s, action, s1):
        """The distance (cost) to go from s to s1."""
        return 1
    
    def h(self, node):
        "Straight-line distance between state and the goal."
        return straight_line_distance(node.state, self.goal)


def make_locations(rows, cols) -> dict:
    all_positions = [(i, j) for i in range(rows) for j in range(cols)]
    
    # Generate all unique pairs of positions
    pairs = tuple(combinations(all_positions, 2))

    return pairs


def make_pairs(rows, cols) -> dict:
    pairs = {}

    # Iterate through all positions in the grid
    for i in range(rows):
        for j in range(cols):
            adjacent = []

            # Check the cell to the right (horizontal neighbor)
            if j + 1 < cols:
                adjacent.append((i, j + 1))

            # Check the cell to the left (horizontal neighbor)
            if j - 1 >= 0:
                adjacent.append((i, j - 1))

            # Check the cell below (vertical neighbor)
            if i + 1 < rows:
                adjacent.append((i + 1, j))

            # Check the cell above (vertical neighbor)
            if i - 1 >= 0:
                adjacent.append((i - 1, j))

            # Store the adjacent pairs for this position
            pairs[(i, j)] = tuple(adjacent)

    return pairs


class Grid:

    def __init__(self, rows, cols):
        self.neighbors = make_pairs(rows,cols)
        self.locations = make_locations(rows,cols)
    
    
def straight_line_distance(A, B):
    "Straight-line distance between two points."
    return sum(abs(a - b)**2 for (a, b) in zip(A, B)) ** 0.5


def manhattan_distance(row1: int, col1: int, row2: int, col2: int) -> int:
    """Distance between two cells when moving only horizontally/vertically."""
    return abs(row2 - row1) + abs(col2 - col1)


# Hamilton cycle generated by AI
def hamiltonian_cycle(rows, cols, start_row, start_col):
    # Quick feasibility check
    if rows * cols == 1:
        return [(start_row, start_col)]
    
    if rows > 1 and cols > 1 and rows % 2 == 1 and cols % 2 == 1:
        raise ValueError  # No Hamiltonian cycle possible

    total_cells = rows * cols
    start = (start_row, start_col)
    path = [start]
    visited = set(path)

    directions = [(-1, 0), (1, 0), (0, -1), (0, 1)]

    def is_valid(r, c):
        return 0 <= r < rows and 0 <= c < cols and (r, c) not in visited

    # DFS
    def backtrack():
        if len(path) == total_cells:
            # Check if last cell connects back to start
            r, c = path[-1]
            sr, sc = start
            if abs(r - sr) + abs(c - sc) == 1:
                path.append(start)  # Close the cycle
                return True
            return False

        r, c = path[-1]

        for dr, dc in directions:
            nr, nc = r + dr, c + dc
            if is_valid(nr, nc):
                visited.add((nr, nc))
                path.append((nr, nc))

                if backtrack():
                    return True

                visited.remove((nr, nc))
                path.pop()

        return False

    if backtrack():
        path.pop()
        return path
    else:
        raise ValueError
    

class PriorityQueue:
    """A queue in which the item with minimum f(item) is always popped first."""

    def __init__(self, items=(), key=lambda x: x): 
        self.key = key
        self.items = [] # a heap of (score, item) pairs
        for item in items:
            self.add(item)
         
    def add(self, item):
        """Add item to the queuez."""
        pair = (self.key(item), item)
        heapq.heappush(self.items, pair)

    def pop(self):
        """Pop and return the item with min f(item) value."""
        return heapq.heappop(self.items)[1]
    
    def top(self): return self.items[0][1]

    def __len__(self): return len(self.items)

    
# Best first from homework
def best_first_search(problem, f):
    "Search nodes with minimum f(node) value first."
    node = Node(problem.initial)
    frontier = PriorityQueue([node], key=f)
    reached = {problem.initial: node}
    while frontier:
        node = frontier.pop()
        if problem.is_goal(node.state):
            return node
        for child in expand(problem, node):
            s = child.state
            if s not in reached or child.path_cost < reached[s].path_cost:
                reached[s] = child
                frontier.add(child)
    return failure


def breadth_first_bfs(problem):
    "Search shallowest nodes in the search tree first; using best-first."
    return best_first_search(problem, f=len)


def g(n): return n.path_cost


def astar_search(problem, h=None):
    """Search nodes with minimum f(n) = g(n) + h(n)."""
    h = h or problem.h
    return best_first_search(problem, f=lambda n: g(n) + h(n))


def depth_first_bfs(problem):
    "Search deepest nodes in the search tree first; using best-first."
    return best_first_search(problem, f=lambda n: -len(n))
